services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-minitwit
    ports:
      - 5000:5000
    volumes:
      - .:/minitwit

  simulator:
    build:
      context: .
      dockerfile: Dockerfile-simulator
    volumes:
      - ./API_Spec:/api_spec