services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-minitwit
    ports:
      - 5000:5000
    volumes:
      - .:/minitwit
    command: python3 manage.py migrate --run-syncdb && python3 ./manage.py runserver 0.0.0.0:5000
    networks:
      - djangonetwork
    links:
      - db:db
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:15.2
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    networks:
      - djangonetwork

  simulator:
    build:
      context: .
      dockerfile: Dockerfile-simulator
    volumes:
      - ./API_Spec:/api_spec
    profiles: ["simulator"]
  
networks:
  djangonetwork:
      driver: bridge