version: "3.8"

services:
  server:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit
    ports:
      - 5000:5000
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        sleep 5
        python3 ./manage_prod.py migrate --run-syncdb
        python3 ./manage_prod.py runserver 0.0.0.0:5000 --insecure
    networks:
      - djangonetwork
    links:
      - db:db
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:15.2
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    networks:
      - djangonetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  djangonetwork:
      driver: bridge