version: "3.8"

services:
  server:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit
    ports:
      - 5000:5000
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        sleep 5
        python3 ./manage_prod.py migrate --run-syncdb
        python3 ./manage_prod.py runserver 0.0.0.0:5000 --insecure
    networks:
      - djangonetwork
    links:
      - db:db
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:15.2
    container_name: db
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    networks:
      - djangonetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - djangonetwork

  grafana:
    image: grafana/grafana:4.5.2
    restart: always
    ports:
      - 3000:3000  
    networks:
      - djangonetwork

networks:
  djangonetwork:
      driver: bridge

volumes:
  database:
    external: true