name: Testing

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start server
        run: DOCKER_DEFAULT_PLATFORM=linux/arm64 docker compose up --build --wait
      
      - name: Simulation test
        run: DOCKER_DEFAULT_PLATFORM=linux/arm64 docker compose up simulator --build

      - name: Cleanup
        run: docker compose down

