name: Testing

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start server
        run: docker compose up --build -d --wait
      
      - name: Simulation test
        run: docker compose up simulator --build

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: minitwitimage

      - name: Cleanup
        run: docker compose down

  # security:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Build a Docker image
  #       run: docker build -t ./src .
  #     - name: Run Snyk to check Docker image for vulnerabilities
  #       uses: snyk/actions/docker@master
  #       env:
  #         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  #       with:
  #         image: src/Dockerfile